const creepypastas = [
    {
      id: 1,
      titulo: 'The Russian Sleep Experiment',
      autor: 'Desconhecido',
      categoria: 'Científica, Experimento',
      tamanho: 10500,
      dataPublicacao: 2010,
      popularidade: 'Muito Alta',
      origem: 'Internet (fóruns)',
      verificado: false,
    },
    {
      id: 2,
      titulo: 'Smile Dog',
      autor: 'Desconhecido',
      categoria: 'Entidade, Imagem Assombrada',
      tamanho: 3800,
      dataPublicacao: 2008,
      popularidade: 'Muito Alta',
      origem: 'Internet (fóruns)',
      verificado: false,
    },
    {
      id: 3,
      titulo: 'Borrasca',
      autor: 'CK Walker',
      categoria: 'Mistério, Lenda Urbana',
      tamanho: 82000,
      dataPublicacao: 2012,
      popularidade: 'Muito Alta',
      origem: 'Reddit',
      verificado: true,
    },
    {
      id: 4,
      titulo: 'NoEnd House',
      autor: 'Brian Russell',
      categoria: 'Sobrenatural, Casa Assombrada',
      tamanho: 9500,
      dataPublicacao: 2013,
      popularidade: 'Alta',
      origem: 'Reddit',
      verificado: true,
    },
    {
      id: 5,
      titulo: 'Gateway of the Mind',
      autor: 'Desconhecido',
      categoria: 'Científica, Experimental',
      tamanho: 4200,
      dataPublicacao: 2010,
      popularidade: 'Média',
      origem: 'Internet (fóruns)',
      verificado: false,
    },
    {
      id: 6,
      titulo: 'Psychosis',
      autor: 'Desconhecido',
      categoria: 'Psicológica, Terror',
      tamanho: 8800,
      dataPublicacao: 2010,
      popularidade: 'Média',
      origem: '4chan',
      verificado: false,
    },
    {
      id: 7,
      titulo: 'The Harbinger',
      autor: 'Desconhecido',
      categoria: 'Criatura, Folclore',
      tamanho: 2700,
      dataPublicacao: 2010,
      popularidade: 'Média',
      origem: 'Internet (fóruns)',
      verificado: false,
    },
    {
      id: 8,
      titulo: 'The Expressionless',
      autor: 'Desconhecido',
      categoria: 'Sobrenatural, Lenda Urbana',
      tamanho: 1900,
      dataPublicacao: 2010,
      popularidade: 'Média',
      origem: 'Reddit',
      verificado: false,
    },
    {
      id: 9,
      titulo: 'Normal 🌽 for Normal People',
      autor: 'Desconhecido',
      categoria: 'Psicológica, Terror',
      tamanho: 4500,
      dataPublicacao: 2012,
      popularidade: 'Alta',
      origem: 'Reddit',
      verificado: false,
    },
    {
      id: 10,
      titulo: 'Autophobia',
      autor: 'Matt Dymerski',
      categoria: 'Psicológica, Terror',
      tamanho: 11000,
      dataPublicacao: 2013,
      popularidade: 'Média',
      origem: 'Reddit',
      verificado: true,
    },
  ];


export default { creepypastas }